#!/bin/sh
export PRIMARY_DISPLAY="eDP1"
export SECONDARY_DISPLAY="HDMI1"

export GTK_IM_MODULE='fcitx'
export QT_IM_MODULE='fcitx'
export XMODIFIERS='@im=fcitx'

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

exec i3
exec start-pulseaudio-x11
