export EDIOR=vim

if [ -n "$XDG_VTNR" ] && [ "$XDG_VTNR" -eq 1 ]; then
  exec startx &> /dev/null
fi
if [ -n "$XDG_VTNR" ] && [ "$XDG_VTNR" -eq 2 ]; then
  exec nvidia-xrun &> /dev/null
else
  setterm -cursor on
fi
