#Android SDK path when installing from AUR
export ANDROID_HOME=/opt/android-sdk

#Tab Completion and File/Directory appearance
autoload -U compaudit compinit
source $XDG_CONFIG_HOME/zsh/completion.zsh
source $XDG_CONFIG_HOME/zsh/theme-and-appearance.zsh
compinit -i -d "${ZSH_COMPDUMP}"

#Custom Prompt with powerline-go
function powerline_precmd() {
    PS1="$(/usr/bin/powerline-go -error $? -shell zsh -modules cwd,git)"
}

function install_powerline_precmd() {
  for s in "${precmd_functions[@]}"; do
    if [ "$s" = "powerline_precmd" ]; then
      return
    fi
  done
  precmd_functions+=(powerline_precmd)
}

if [ "$TERM" != "linux" ]; then
    install_powerline_precmd
fi


bindkey -v

export XAUTHORITY=/home/piri/.Xauthority
export DISPLAY=:0.0

export ASIO_INCLUDE_PATH=/home/piri/nvs5/asio/asio/include
export SPDLOG_INCLUDE_PATH=/home/piri/nvs5/spdlog/include
export FMT_PATH=/home/piri/nvs5/fmt
export JSON_INCLUDE_PATH=/home/piri/nvs5/json/src

alias bnet="setarch i386 -3 wine ~/.wine/drive_c/Program\ Files\ \(x86\)/Blizzard\ App/Battle.net\ Launcher.exe"
alias toff="synclient TouchpadOff=1"
alias ton="synclient TouchpadOff=0"
alias updt="newsbeuter && sudo pacman -Syyu"
alias "frt"="fortune | ponysay -f owl"
frt
